services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tea_web_dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"