services:
  react_app:
    image: zstin4/tea-web:${IMAGE_TAG}
    container_name: tea-web-main
    restart: always
    expose:
      - "80"
    networks:
      - web

networks:
  web:
    external: true
    name: web