services:
  react_app:
    image: zstin4/tea-web:${IMAGE_TAG}
    container_name: tea_web_staging
    restart: always
    expose:
      - "80"
    networks:
      - backend

networks:
  backend:
    external: true
    name: backend