version: "3.8"

services:
  react_app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: tea_web
    restart: always
    expose:
      - "80"
    networks:
      - backend

networks:
  backend:
    external: true
    name: backend