sonar.projectKey=Tea-web
sonar.projectName=The Tip Top - Frontend
sonar.projectVersion=1.0

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.*,**/*.spec.*
sonar.tests=src
sonar.test.inclusions=**/*.test.*,**/*.spec.*

sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=coverage/lcov.info